name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fbfc71e8212145fce93a51f966c0dd4a19a1499205c487214ebd3f2cb53080b"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
