name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03ab5f32c4ace252aec75422648165d505ecca2e7261ff93933a368c3d17072a"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
