name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f91990a4fe897b66a7ce66837959f1b46734bb1c69049e0c71486f2a176ce622"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
