name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac8260eae00b9aa0acd86fa9da94ee67dc8a5e2b0bbe8a1fb4d7a2ee11cb95e3"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
