name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c031f9cdefc2693ebfd84bac611de0f1fea36b2bd78382b08198270966fa1cae"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
