name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e73651debb591d26297cf69ac256313c3d7ecf1a5e1ab3a7adc349ec6e0f825c"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
