name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b7e9159cbf2d6dc049075b0b4eef93d939d6a37bab042a9d71bd4ad0384095b"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
