name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4bf8e29468dbf1c87ef8d39ad02759b71e5f69cb296ce3f18a7ba54f17a077d"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
