name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28eec9a4163358b4710f0eda01ff9fa6586fd97f56534cee1139da4041d5b998"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
