name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeb0d63f333d28eaf4dfff35830b64e7bda2ee7fa7420eab815d91d97ff55329"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
