name = "Basepack"
author = "Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "304a2eb71a7ad328dd1565037f4e8dfaea73155c693a302e1152f7f1ee2d640f"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
