name = "Basepack"
author = "Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52ad0fe20e078d09065c5779ddc12a9069e957e5de94791b299ab6a3f7ec6a04"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
