name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08c82fcecd991e1568b54427513e893da33b806f5e440ade25c6361d497bb968"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
