name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13232fd2090b952f072a6ac3cfcfd9a71729f6dc3f02bcfb5ec11a145e90756b"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
