name = "Basepack"
author = "Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dce2a369df3f299341ecc244972068c411ccdb9ff1c83a003ab198ed90e8617c"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
