name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02268983a7ba6463161fc5ded9cd1103ecc91672c079d4e78ae6ee9e3f604ac9"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
