name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "638264e3775bf5a7ea817fa1b65bdb19b23d524a50e52130e3760385164cafd5"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
