name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "185547ec5bcad204ac92c64ea32650e85666db83df1ca77e4201bf4835c22772"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
