name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4cafb50415470bd061989b90d74eab3a2443214cbf0ede5ef312bde924b99c6"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
