name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33dbd934019d34c099401c5b76b50b44d3e1b17125d09f32f8b7fbaadedc9b17"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
