name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f99c83a56b43d63f697368a57ffd4e36885f02aae3ab383c00ce6e150fbada3e"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
