name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edf24bfb44bdf893c82779555b65daf335d207c0582b2125bb7c38a1fa1d63ad"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
