name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c760af9579a5c789dee29c33853f4bae989eb39ba2de55788cb5c5efbfbbe66"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
