name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "696b1978011182c9aa7f732a98b00b2954927ecbb0e42a64835220a6ad2dd234"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
