name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e689d06c8b99a3d6adf6450e969e568af3e399dcbbcdb006ed0ac737d6b78a82"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
