name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29cbf1f59eefb4594d71495bd0004e10280f8949ee8d373e4fc3c45e5a3dfb80"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
