name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b1315c7f2197c32fcffa29fc0d1cc40db7c31c373b7c7799ca0c299d86fc2f"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
