name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d7c03c155f8c41a586de63d559fbd0c7a620dedde6fe31b3fb8622df71ad27a"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
