name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df8587115ce3eda427328a3d41fda55a760c2020c7087151102fbd1845e2bcfd"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
