name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d773d8d0c0f3b51ab2e66b8ef08ec1db0724e8b334d01620c66718c6dc963b92"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
