name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10456aa84db78a2fad19ae39404d05a9fb5a63fcf6d1b319ee53c53741cdf83a"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
