name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03e9a8c20398fcb1799720d5cecdb2519051f27775af9167ecf1d6f5f61743fe"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
