name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5db9fae48893a3135c7b8a3d1d62df81ab329ba81b67f49259a6d7914d4c6bd6"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
