name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1df94c13dda14f203b8f342d419b84d6dd7c0d3ba29202f5718ee71278a1785b"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
