name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd7f2a412248668f960d74dad96695bf11c70c048ac191b121c03d03f02d4cba"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
