name = "Basepack"
author = "Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbe07385b135f3f44b9e50b3be8ffcbcff7cd62ddf4fecd75ce9c132302f9202"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
