name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b283f7959f5932be8bb0896893fb79466d2b7b34847afc8cfb8c77f304060cc"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
