name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36ed35c4f3a96dc6d5cdf4761494bd292ba917df71e42c203add009932c44316"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
