name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bf1ef4581d0c48f7c054da6629b29f09f89a9bbfd90f960f2cce98198c3b58c"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
