name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c564a4cdcd7b4adb6e160488e20695fd4327d5ef212cf6255c27d6bca6579206"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
