name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22219fd20c48212ce084aecbc80a74c5fe6e95681f2ace0aef7a952323a892c0"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
