name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f56b7d53d05defd795062cf831efdc3b16f6a10dbcfea07c98b11ee270ae6c0d"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
