name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd3d8c9cabaa00aaaa0ebfbeef0901f73f1a418859e6410070e6d2bab53dac1f"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
