name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcd3b0d5482d9d57a2029968daada6a70850074d4f9a06b7870c5653864a7a6a"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
