name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "797b3e61e62bbba967e41001c5081cdfa169c1a8fc3686a0eca8d7e904f1159f"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
