name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bacc32d9a73515128475e62385386f5cd5f5cb38bd9afd6bce221494d0b19708"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
