name = "Basepack"
author = "Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34fdaab822185a3dac7ab8f70c8b466132f4f9e8e095dabb01b52074cf5204a4"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
