name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b54a25bf39aee7468eaa5872a8d460bc5d91118831c4e79ee7abf5b8b2f60897"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
