name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "432aa15b2e28a1d749e785ddc04ea548d15a85bcca5f094319721c18c5b3ddc6"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
