name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80d3681050b85bb1fdc8a1680e062424e5ad46993f02d7ddda44546628d39b13"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
