name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8102f5bab0cb74672c88d4b5f833beadb52a6591de77a2489a0bea6290bb15c0"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
