name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7569bbdb6f57551d6cbca525562591a1fb1e60c918ce0e2614ff381807d2a4d6"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
