name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c40c8c62274881e9ca268b3f650ea936740e9f81ff830e75818d76bd3e803d62"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
