name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28b2234e2cc747307421684fcd061620005e00dcedd76769f9d7dd165ba192e8"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
