name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aab9ec4257563a260b2a0d274c5b28b91441049bd0387d11e4510bceb4fe112"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
