name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9d1ab062ed9f5ed5919f6f30602f5258d8abedb63f519db7290c6ff7f0f25b8"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
