name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9165c2f855311f9615cdcec11fcc6e6d3a6edcde8a07d1a77a9e1023d3fb68e0"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
