name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b547f8fefab62afd80456de243bd35ece5d0b1d7f8b524479daaf38f967c023b"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
