name = "Basepack"
author = "Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4152d240ee49cc6b79128c501b218d653f801e9f934f3afb69a3b1653388583"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
