name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c088fec607a188a39ae462ecfe2869472f7ef01a36754c799b549a503b95e06f"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
