name = "Terralon"
author = "verbina29, AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9c3901b6394a3ed1fc009f563d68db34c470edfd3e5a1d1a82602a670e18181"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0-beta.1"
