name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8eb302156d19c3fedf0cbd02efe758fc9d1f3d4e2892660dc90bbabce093189"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
