name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18c58dcf206d82d9ff775d7891c7d1fb52f622ad0c395b0fba441bc161a5c681"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
