name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fb6d2212c88aa3f85da19370be9c9c2893cae57e674b13c6abb6bd998b88897"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
