name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "863653bbc8b5f4a1974373ec56b3cbd716534b1d90bc3cc3198ff6abfc9207eb"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
