name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71062534eaed7042071470a9f9af13e88ad0edfc50ce3df0f074cba4a9f3b4a7"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
