name = "Basepack"
author = "Verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40827c733c248a23f3a8bae994a2fe613970617aa9aade02376de0829d70e08c"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
