name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8905f01279afbf3814b689392252e1bba24e264fd76d1ad0a465640e8df22c8b"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
