name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "701e9f49dc6f780964d20098c2755b814c9df846e9404634045a9e4b9d2a686c"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
