name = "Terralon"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c35ce97b63ccc9f552759254aa3771abbc2c92683c82743bebe810622c100354"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
