{
  "merc_biomes": [
  ],
  "merc_spawn_weight": 0,
  "merc_min_group": 0,
  "merc_max_group": 0,
  "spy_biomes": [
  ],
  "spy_spawn_weight": 0,
  "spy_min_group": 0,
  "spy_max_group": 0,
  "lesser_biomes": [
  ],
  "lesser_spawn_weight": 0,
  "lesser_min_group": 0,
  "lesser_max_group": 0,
  "greater_biomes": [
  ],
  "greater_spawn_weight": 0,
  "greater_min_group": 0,
  "greater_max_group": 0,
  "merc_health": 20.0,
  "merc_exp": 4,
  "spy_health": 20.0,
  "spy_exp": 4,
  "lesser_health": 48.0,
  "lesser_exp": 8,
  "greater_health": 100.0,
  "greater_exp": 16,
  "rocket_breaks": true,
  "balrog_breaks": false,
  "grenades_breaks": false,
  "bullets_breakdripstone": true,
  "bullets_disable_iframes_on_players": true,
  "pistol_damage": 5.0,
  "golden_pistol_damage": 5.1,
  "silenced_pistol_damage": 5.0,
  "luger_damage": 5.0,
  "ak47_damage": 4.0,
  "sniper_damage": 20.0,
  "sniper_scoped_damage": 30.0,
  "minigun_damage": 2.0,
  "smg_damage": 2.0,
  "hellhorse_damage": 7.0,
  "tommy_damage": 2.0,
  "shotgun_damage": 6.0,
  "meanie_damage": 3.0,
  "balrog_damage": 8.0,
  "brimstone_damage": 3.0
}